# This file defines the menus on the website. See the documentation for
# details: http://docs.bolt.cm/menus

main:
  - label: Home
    path: homepage
  - label: Blauw-Rode Kamer
    path: blauw-rode-kamer.html
  - label: Turquoise Kamer
    path: turquoise-kamer.html
  - label: Omgeving
    path: omgeving.html
  - label: "Reserveren & contact"
    path: reserveren-en-contact.html
  - label: "Fotoalbum"
    path: fotoalbums.html
  - label: "Links"
    path: links.html
